### ISSUE TITLE
Test suite regression

### ISSUE THREAD

**Issue by 1ma** [beanstalkd/beanstalkd#618] opened 2022-01-08 12:27 UTC
A change introduced in this commit https://github.com/beanstalkd/beanstalkd/commit/4c275d5945299e4562389f9f2ca7c326173d6335 broke the test suite:

```
ct/_ctcheck
....................................................................F...............................

cttest_stats_tube: failure
start server port=38419 pid=284
>72 use tubea
<72 USING tubea
>72 put 0 0 0 1
>72 x
<72 INSERTED 1
>72 delete 1
<72 DELETED
>72 stats-tube tubea
<72 OK 265
<72 ---
name: "tubea"
current-jobs-urgent: 0
current-jobs-ready: 0
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
total-jobs: 1
current-using: 1
current-watching: 0
current-waiting: 0
cmd-delete: 1
cmd-pause-tube: 0
pause: 0
pause-time-left: 0

testserv.c:330: test: strstr(line, sub)
testserv.c:330: "
name: tubea
" not in "---
name: "tubea"
current-jobs-urgent: 0
current-jobs-ready: 0
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
total-jobs: 1
current-using: 1
current-watching: 0
current-waiting: 0
cmd-delete: 1
cmd-pause-tube: 0
pause: 0
pause-time-left: 0

"

1 failures; 0 errors.
make: *** [Makefile:95: check] Error 1
```

It would probably be worthwhile to clean up the extant Travis configuration and set up a new CI pipeline elsewhere, like GH Actions.

**Comment by SamMousa** [comment] 2022-01-27 10:18
I've already created a PR for setting up Github Action CI here: #613 

Interestingly because that wasn't merged I didn't catch the regression (even though I think I did run the tests locally...)

Will create a PR to fix it but we should merge #613 first...

**Closed** 2022-11-25 15:20 UTC
Labels: NeedsFix
