### ISSUE TITLE
move command

### ISSUE THREAD

**Issue by JalfResi** [beanstalkd/beanstalkd#170] opened 2013-02-15 19:08 UTC
The following suggestion was made by gcatlin@gmail.com on the beanstalk-talk mailing list (https://groups.google.com/group/beanstalk-talk/browse_thread/thread/326616f87ba8b6e/d94c2f41b88f62e5?lnk=gst&q=move+tube#d94c2f41b88f62e5). 

After looking for exactly this feature request in the issues list and mailing list I took the liberty of copying and pasting gcatlin's request below:

Is there any plan to support atomically moving a job from one tube to 
another? This would be really useful to make routing jobs between 
tubes safer and more efficient. I'm imagining a "move" operation for a 
reserved job. It would be very similar to "release", but instead of 
returning the job to the tube from which it was reserved, it would 
move the job to the end of the currently used tube. 
Here's some hypothetical documentation: 
The "move" command moves a reserved job into the ready queue of the 
currently 
used tube. It is normally used when routing jobs between tubes. It 
looks like this: 
move <id> <pri> <delay> <ttr>\r\n 
- <id> is the job id to move. 
- <pri> is a new priority to assign to the job. 
- <delay> is a new integer number of seconds to wait before putting 
  the job in 
  the ready queue. The job will be in the "delayed" state during this 
  time. 
- <ttr> -- time to run -- is an integer number of seconds to allow a 
  worker 
  to run this job. This time is counted from the moment a worker 
  reserves 
  this job. If the worker does not delete, release, or bury the job 
  within 
  <ttr> seconds, the job will time out and the server will release 
  the job. 
  The minimum ttr is 1. If the client sends 0, the server will 
  silently 
  increase the ttr to 1. 
  The client expects one line of response, which may be: 
- "MOVED\r\n" to indicate success. 
- "BURIED\r\n" if the server ran out of memory trying to grow the 
  priority 
  queue data structure. 
- "NOT_FOUND\r\n" if the job does not exist or is not reserved by the 
  client. 
  Thoughts?

**Comment by ysmolsky** [comment] 2019-07-01 16:25
dupe of #240. closing as the other issue has better formatted text.

**Closed by ysmolsky** 2019-07-01 16:25 UTC
