### ISSUE TITLE
Could we have beanstalkd offical Docker images in Docker Hub?

### ISSUE THREAD

**Issue by tonytonyjan** [beanstalkd/beanstalkd#596] opened 2020-12-15 06:48 UTC
There are lots of [unofficial images](https://hub.docker.com/search?q=beanstalkd&type=image) in Docker Hub already but most of them are outdated and not well maintained. To get the newest stable beanstalkd image, people have to either clone, build, and push to some image registry or trying to find a suitable one in Docker Hub. Either way would cost time.

I wonder if there is any future plan for official Docker images hosting?

**Comment by ysmolsky** [comment] 2020-12-16 08:28
Dupe of #589

**Closed by ysmolsky** 2020-12-16 08:28 UTC
