### ISSUE TITLE
Degradation on many tubes

### ISSUE THREAD

**Issue by bessudnov** [beanstalkd/beanstalkd#561] opened 2019-09-03 23:12 UTC
I have tried to create about 1500 tubes and than run 300 instances of simpliest php code.
```
$connection = new \Pheanstalk\Pheanstalk(
    'host',
    11300,
    5,
    false
);


while (true) {
$queue = 'test' . rand(1,2000);
    $job = $connection
        ->watch($queue)
        ->ignore('default')
        ->reserve();


    echo microtime(true) . ' PUT START'. PHP_EOL;

$before = microtime(true);


    $connection->putInTube(
        'test' . rand(1, 2000),
        $job->getData()
    );
$after = microtime(true);
$delta = $after - $before;
echo 'DELTA = ' . $delta . PHP_EOL;

    $connection->delete($job);
} 
```

Results was bad:
1 instance:
1567547165.0457 PUT START
string(20) "INSERTED 820713869
"
DELTA = 0.0016741752624512
1567547165.0474 PUT FINISH

300 instances
1567547210.9205 PUT START
string(20) "INSERTED 820886790
"
DELTA = 0.021309852600098
1567547210.9419 PUT FINISH

Time for inserting increased more than 10 times.

Can anyone suggest where can be the problem.

**Comment by ysmolsky** [comment] 2019-09-04 08:36
I am sorry, but your benchmark has some flaws. On each iteration of "while" you print out delta. Instead you should sum deltas for all iterations in one instance and then at the end print out the average delta. This might give you better picture. 

Another thing. If you run 300 instances concurrently, it means that instances compete against each other. And any given instance have to wait until some instances are done with server. I do not know what are you trying to measure with this benchmark, knowing that might help me to give better advice how to use beanstalkd efficiently. 

Also reconsider the way you implemented jobs reservation. In your algorithms job is reserved randomly, meaning that on average just a few instances are actually running concurrently. Most of the time they are waiting for the job to appear in the random tube.

**Comment by bessudnov** [comment] 2019-09-05 11:51
> I am sorry, but your benchmark has some flaws. On each iteration of "while" you print out delta. Instead you should sum deltas for all iterations in one instance and then at the end print out the average delta. This might give you better picture.

Ok, delta is not the correct word to use here. I measure just the time of put operation.

> Another thing. If you run 300 instances concurrently, it means that instances compete against each other. And any given instance have to wait until some instances are done with server. I do not know what are you trying to measure with this benchmark, knowing that might help me to give better advice how to use beanstalkd efficiently.

I try to measure the time of inserting data on many processes that inserts data into different tubes. Do you mean that beanstalkd is not multithreaded and performs operations consistently one by one?

> Also reconsider the way you implemented jobs reservation. In your algorithms job is reserved randomly, meaning that on average just a few instances are actually running concurrently. Most of the time they are waiting for the job to appear in the random tube.

I put jobs before the test, that is why code doesnt wait for them.

**Comment by ysmolsky** [comment] 2019-09-05 14:21
beanstalkd is event based, so all operation are consequential. But it is very fast nevertheless, when client is in C, then you can achieve performance of 4k (put-delete) ops/second with data persistency (WAL) turned on according to benchmarks we have: https://travis-ci.org/beanstalkd/beanstalkd/jobs/580909339

**Comment by ysmolsky** [comment] 2019-09-05 14:24
This ticket is not actionable. I cannot see what can be done on my side. @bessudnov I suggest you to ask pheanstalkd authors: https://github.com/pheanstalk/pheanstalk

**Comment by bessudnov** [comment] 2019-09-05 15:39
Well, its fast on one tube, but when there hundreds and thousands of tubes - here is the problem.

I tried to use python and have the same error, increasing number of instances of python script, put command start working slower.

```#!/usr/bin/env python
from telnetlib import Telnet
from datetime import datetime
import time
import random

con = Telnet('127.0.0.1', 11300)

while True:
     num = str(random.randint(1, 1000))
     con.write("watch test" + num + "\r\n")
     con.write("reserve\r\n")
     con.write("use tube test" + num + "\r\n")
#     ;dt = datetime.now()
#     ;print dt.microsecond
     ts1 = time.time()
     data = "test"
     lengh = str(len(data.encode('utf-8')))
     con.write("put 1024 0 60 " + lengh + "\r\n" + data + "\r\n")
     d = con.read_until("INSERTED"),
     ts2 = time.time()
     print(" ".join(d), ts2-ts1)```

**Comment by ysmolsky** [comment] 2019-09-05 15:51
Again your program does not measure anything because it depends on the way you run clients and how jobs are added to tubes, etc. From your code I can say that this is not a good benchmark and does not prove any point. It is expected that the single put command will be slower when you have thousands of concurrent clients competing for the same resource. 

Please show me some meaningful results along with source code so I can understand your point.

What problem are you trying to solve?

**Comment by kr** [comment] 2019-09-05 23:09
Function `tube_find` does a linear scan through the list of all tubes to look up a tube by name. It gets slower when there are many tubes. Normally this doesn't happen when reserving a job, because each client connection has its own list of watched tubes. But if the client is issuing many `watch` commands (or other commands that need to look up tubes), that might be relevant.

Does the client in this case run `watch` for each reservation? For instance, maybe it opens a new connection for each reservation and therefore needs to run the watch command each time.

**Comment by ysmolsky** [comment] 2019-09-06 06:34
This what I understood from our  conversation in Twitter: author uses > 10k tubes, each worker connects, "watch" some tube, "reserve" the job, disconnects. In that case "tube_find" might be the bottleneck.

**Comment by ysmolsky** [comment] 2019-09-06 07:32
It is not only performance of `tube_find` is degraded in case of big amount of tubes. `soonest_delayed_job` is affected as well, as it scans through all the tubes. And `next_awaited job`: it picks the job with smallest priority among all awaited jobs in all tubes. `next_awaited job` is called by `process_queue`, and that is called when job is added and reserved too.

Amount of tubes affects performance of these functions linearly.

**Comment by ysmolsky** [comment] 2019-09-06 08:28
Reproducing this in our benchmarks. I have injected this code to `bench_put_delete_size` just before actual benchmark. It watches for T amount of tubes. It does not put jobs in them. Everything happens in the default tube.
```
    for (i = 0; i < T; i++) {
        sprintf(buf, "watch tube%d\r\n", i + 1);
        mustsend(fd, buf);
        ckrespsub(fd, "WATCHING ");
    }
```
T=0:
```
ctbench_put_delete_0008	    5000	    335256 ns/op	   0.04 MB/s
ctbench_put_delete_1024	    3000	    338097 ns/op	   3.07 MB/s
ctbench_put_delete_8192	    3000	    378445 ns/op	  24.25 MB/s
```

T=1000:
```
ctbench_put_delete_0008	    5000	    392244 ns/op	   0.04 MB/s
ctbench_put_delete_1024	    5000	    390163 ns/op	   4.68 MB/s
ctbench_put_delete_8192	    3000	    423477 ns/op	  23.93 MB/s
```

T=10000:
```
ctbench_put_delete_0008	    2000	    916187 ns/op	   0.01 MB/s
ctbench_put_delete_1024	    2000	    910175 ns/op	   1.89 MB/s
ctbench_put_delete_8192	    2000	    855391 ns/op	  15.30 MB/s
```

Then instead of watching tubes in the connection where benchmarking is performed, I have created another connection where T tubes were just watched.
T=1000:
```
ctbench_put_delete_0008	    5000	    392381 ns/op	   0.04 MB/s
ctbench_put_delete_1024	    5000	    393842 ns/op	   4.67 MB/s
ctbench_put_delete_8192	    3000	    431670 ns/op	  23.87 MB/s
```

T=10000:
```
ctbench_put_delete_0008	    2000	    957047 ns/op	   0.01 MB/s
ctbench_put_delete_1024	    2000	    910631 ns/op	   1.89 MB/s
ctbench_put_delete_8192	    2000	    867341 ns/op	  15.26 MB/s
```

This proves the point that amount of tubes affects regular put/reserver operations. Performance is reduced: 1.2 times for 1k tubes, 3 times for 10k tubes.

**Comment by ysmolsky** [comment] 2019-09-14 04:55
@bessudnov did any of the above help you in some way?

**Comment by ysmolsky** [comment] 2019-12-17 09:40
Closing as not actionable issue. I won't fix this because it requires architecture overhaul.

**Closed by ysmolsky** 2019-12-17 09:40 UTC
