### ISSUE TITLE
project maintenance going forward?

### ISSUE THREAD

**Issue by petri** [beanstalkd/beanstalkd#385] opened 2018-06-08 13:19 UTC
While beanstalkd is mature software, there is always need for some love as evidenced by the number of long-standing open issues and PRs.

@kr would you have any suggestions as to what the community could and/or should do? Is there anything you think you could do to support or facilitate that?

Thank you.

**Comment by pmatseykanets** [comment] 2018-06-09 03:17
#335

**Comment by pprindeville** [comment] 2018-08-01 18:37
Related #383

**Comment by pprindeville** [comment] 2018-08-01 18:38
What about adding a 2nd maintainer who has a long-standing involvement in the project and the author trusts?

**Comment by JensRantil** [comment] 2018-08-15 17:26
I believe this is a duplicate of #299.

**Comment by JensRantil** [comment] 2018-08-17 12:32
Closing this. The original maintainer, @kr, has added me as an additional maintainer.

**Closed by JensRantil** 2018-08-17 12:32 UTC
