### ISSUE TITLE
Beanstalk not purging old binlogs?

### ISSUE THREAD

**Issue by laszlof** [beanstalkd/beanstalkd#570] opened 2019-12-27 02:56 UTC
I know this was previously an issue, that was supposed to be fixed in 1.5, However, we're still seeing this happen.

We're currently using beanstalk 1.10, and noticed that our binlog directory has grown to over 265GB in usage.

When looking at beanstalk stats, we have roughly 10K jobs in a delayed state. Even with our maximum job size of 10MB (99.9% of jobs are going to be less than 1 or 2MB each), that only puts us at 100GB of storage.

It appears as though jobs that have been purged, are not being removed from disk.

Is there a safe way to clean up after this? How can we prevent it from happening?

**Comment by laszlof** [comment] 2019-12-27 04:11
Further on this, it seems this started happening a little over a week ago, with seemingly no changes on our end.

**Comment by kr** [comment] 2019-12-27 04:23
Did the start of this disk usage coincide with the accumulation of 10k delayed jobs? Or were that many jobs delayed before the disk usage got so big? What is your normal steady-state disk usage?

**Comment by laszlof** [comment] 2019-12-27 04:28
Sadly I don't have that stat available during that time frame. I'd venture to say that yesz it was at about the 10k delayed job mark.

**Comment by laszlof** [comment] 2019-12-27 04:41
Ok. Just checked things over. I actually do have the data. It doesnt appear that the 17th was anything special with regards to delayed jobs.

There was about 17K delayed jobs in the queue on the date when the disk usage started to spike. That has been gradually increasing over time at pretty much the same rate.

Once the disk was filled, I shutdown the beanstalkd daemon, and removed some of the older binlogs to free up space. This allowed us to go in, and wipe out some older delayed jobs that we did not care about. 

Since doing this, the disk usage seems to have flatlined, but its not giving us any indication as to why it all the sudden decided to spike.

This graph shows our delayed jobs over time. You can see at the end where we purged a large number of them.
<img width="1561" alt="Screen Shot 2019-12-26 at 11 39 20 PM" src="https://user-images.githubusercontent.com/1486486/71501494-f6ac7b80-2838-11ea-90d8-94a8936f7c17.png">

This graph shows disk usage percentage over the same period of time:

<img width="1672" alt="Screen Shot 2019-12-26 at 11 41 11 PM" src="https://user-images.githubusercontent.com/1486486/71501557-3d01da80-2839-11ea-9471-1088b8a11952.png">

**Comment by laszlof** [comment] 2019-12-27 04:45
Furthermore, after inspecting some of the older binlogs, it looks like the jobs inside of them have already ran. Since we encrypt everything inside the queue, it takes a bit of work to figure out what they were, but for the most part, they are non-delayed regular jobs that would have been processed almost immediately and then deleted. It doesnt appear deleting them is actually removing them from the binlogs.

Is this expected behavior?

**Comment by kr** [comment] 2019-12-27 04:45
Oh excellent, thank you for that additional info. Those graphs are strong evidence there is a bug. Unfortunately it will be difficult to fix unless we can find a way to reproduce it. There have been similar reports over the years once or twice before, but so far no one to my knowledge has been able to reproduce it.

As a side note, it is supposed to be always possible to delete jobs even if the disk is full.  Beanstalkd is designed to reserve space for delete records in the log for exactly that purpose. If the delete command ever fails because of disk space, that is a bug.

**Comment by laszlof** [comment] 2019-12-27 04:51
@kr its possible we could have deleted when the space was full. Our tooling may have prevented it for other reasons unrelated to beanstalk itself. I'd not want to call that a bug without more info.

For now, do you know of a way to cleanup the binlogs and purge any already handled jobs from them?

I noticed there a data bit at the beginning of each line, that I assume is the information beanstalk uses populate a struct internally for the job itself.

Is there anyway to determine jobs that have already ran from that?

**Comment by kr** [comment] 2019-12-27 04:53
> Furthermore, after inspecting some of the older binlogs, it looks like the jobs inside of them have already ran. Since we encrypt everything inside the queue, it takes a bit of work to figure out what they were, but for the most part, they are non-delayed regular jobs that would have been processed almost immediately and then deleted. It doesnt appear deleting them is actually removing them from the binlogs.
> 
> Is this expected behavior?

The bin log is an append-only data structure. The way deleting works is we append a shirt record saying “delete job 123”. When beanstalkd restarts, it replays the log in order, so it will first see the record that creates the job, and recreate the job in memory, then it will encounter the delete record and delete the job. (It doesn’t begin processing client requests until the whole log has been replayed, so clients will not see an older state.)

> Once the disk was filled, I shutdown the beanstalkd daemon, and removed some of the older binlogs to free up space.

Does this mean you manually deleted some but not all of the log files in the bin log directory? I am not sure exactly what will happen in that scenario. I didn’t design it explicitly to support that, so is possible that it could cause some strange behavior when beanstalkd restarts. Or it could be fine, but I haven’t thought it all through so I’m not sure right now.

**Comment by laszlof** [comment] 2019-12-27 04:55
> Does this mean you manually deleted some but not all of the log files in the bin log directory? I am not sure exactly what will happen in that scenario. I didn’t design it explicitly to support that, so is possible that it could cause some strange behavior when beanstalkd restarts. Or it could be fine, but I haven’t thought it all through so I’m not sure right now.

Yes. And I had reservations about trying it. I do have the logs backed up just in case, but it didnt appear to break anything as far as I could tell. 

It sounds like binlogs work a lot like they do on mysql for replication. Is there a way to reindex them from the current state so we can purge all the old ones?

**Comment by laszlof** [comment] 2019-12-27 05:05
So I just checked another system we have running the same software. Its been flawless for quite a while. It doesnt do many delayed jobs (mostly just straight to ready-state). It only has 2 binlogs that are using roughly 21MB of disk space. It seems unlikely that that 21MB contains the entire record since its been running. The process itself hasnt been restarted since March 30th of this year, and it handles just as many (if not more) jobs than the other system.

**Comment by laszlof** [comment] 2019-12-27 05:13
I dont think I mentioned it, but there are over 24K binlogs (mostly about 10MB each) on the affect system.

Heres the command line we're using:

```
/usr/bin/beanstalkd -l <IP_HERE> -p 11300 -u beanstalkd -z 536870912 -b /var/lib/beanstalkd/binlog -s 10485760 -f 10
```

**Comment by kr** [comment] 2019-12-27 05:36
> For now, do you know of a way to cleanup the binlogs and purge any already handled jobs from them?

Well this is supposed to happen automatically as beanstalkd deletes files from the log. There isn’t a way to do it manually since that shouldn’t be necessary assuming the compaction works.

If this bug keeps happening it might make sense to add some sort of manual controls for this process but I’m not sure exactly what that would look like. (Since the log is append-only, it’s not possible to delete individual records. All that can be done is to migrate live records to the head of the log and delete an entire file. Any manual controls would have to happen within that design framework, short of a major redesign of how the binlog works.)

**Comment by kr** [comment] 2019-12-27 05:38
Another thing that probably makes sense is to add more visibility into the log structure. Statistics like how many records are live in each file, space used/reserved/dead/etc. Basically all the internal bookkeeping that beanstalkd does should probably be exposed. That might give some clues about how this bug works.

**Comment by laszlof** [comment] 2019-12-27 05:39
Perhaps make a command to dump the current state to a new binlog file, and purge all the old ones?

I'm assuming when you start up beanstalk, and it replays all the logs, it stores all that in memory and no longer needs to reference the binlogs? They're only useful on startup?

**Comment by kr** [comment] 2019-12-27 05:41
> Perhaps make a command to dump the current state to a new binlog file, and purge all the old ones?

Yeah, that would be one option.

> I'm assuming when you start up beanstalk, and it replays all the logs, it stores all that in memory and no longer needs to reference the binlogs? They're only useful on startup?

That’s right.

**Comment by laszlof** [comment] 2019-12-27 15:28
I think what we're going to do is do an export of all job, shutting down beanstalk, deleting all binlogs, and reimporting the export file we created above. That should get us where we want to be and back to nominal disk usage.

Also it looks like our usage is still flatlined, we havent noticed the growth issue come back up again:

<img width="1690" alt="Screen Shot 2019-12-27 at 10 27 51 AM" src="https://user-images.githubusercontent.com/1486486/71522652-972f8980-2893-11ea-9331-af86b54412e8.png">

**Comment by HenriNijborg** [comment] 2019-12-29 17:45
Some time ago we had kind of the same problem, binlogs clogging up the disk space. This was caused by the binlogs not being migrated to new ones. When the difference between the oldest and newest binlog file was getting to big, exceeding a certain size, no binlogs are migrated. This results in huge amounts of binlog files just piling up. 

The fix for this bug has been released with v1.11. Pull request https://github.com/beanstalkd/beanstalkd/pull/278 was the actual fix back in 2015 which was after the release of v1.10. For the timebeing we created some cron jobs checking some things and clean up any tube which wasn't touched by a worker for a while. This currently prevents us from hitting this bug. Somewhere next year we will upgrade to v1.11 but currently still on v1.10.

**Comment by kr** [comment] 2019-12-29 22:48
Ah yes, thanks for remembering and finding that. This might well be a dup of #276 / #278.

**Comment by laszlof** [comment] 2020-01-02 15:07
@HenriNijborg Thanks for the information. Perhaps an upgrade will resolve the issue.

Honestly we've ran beanstalkd in production for > 5 years and never had any problems with it, so it certainly seems like an extremely edgecase situation.

Sadly, beanstalkd-1.11 isnt available as an RPM for CentOS 7, so short of building our own RPM, we wouldnt be able to upgrade it. (We do not typically build from source for maintainability reasons).

For now, I think we're going to just migrate all our existing jobs to a new beanstalkd instance, which will effectively "reset" our binlogs.

**Comment by HenriNijborg** [comment] 2020-01-02 15:48
@laszlof It was the same situation for us. We ran beanstalkd in production for 3+ years with no problems before we ran into this. Back then running about half a million jobs a day.

**Comment by laszlof** [comment] 2020-01-23 21:03
This started happening again a few days ago. We noticed some delayed jobs getting backed up (around 20K) due to an error in our code. We cleaned up the delayed jobs (delayed queue down to less than 10K now), and the disk usage did not go down. We really need to get this sorted out. Any thoughts besides updating to 1.11 and hoping for the best?

**Comment by kr** [comment] 2020-01-24 07:45
Since a bug with exactly this behavior was fixed in 1.11, it seems likely that upgrading will solve your issue.

**Comment by ysmolsky** [comment] 2020-01-24 08:37
One note from old user of 1.10. During many years we never had this problem, but when we migrated to the different OS (AWS-something) it happened a couple of times. Upgrade to 1.11 has solved the issue.

**Comment by laszlof** [comment] 2020-01-24 12:30
Roger that. I'm having our sysops team build an rpm for 1.11 right now. Hopefully that will resolve the problem. Will let you know. 

Thank you both for the help!

**Comment by laszlof** [comment] 2020-01-24 15:04
@ysmolsky do you guys build your own RPMs for RHEL? It would be nice to have an "official" RPM available for 1.11.

**Comment by ysmolsky** [comment] 2020-01-24 16:37
Nope, I deploy using docker container in which I build it from scratch.

**Comment by kevinbosak** [comment] 2020-03-18 14:04
@laszlof Did upgrading to 1.11 resolve your issue?  We just ran into the same thing where one buried job caused the binlogs to fill the disk space.  We're on 1.10. 
This wouldn't have been an issue for us, except that our monitoring was flawed and only reporting 2 or more buried jobs.

**Comment by laszlof** [comment] 2020-03-18 14:09
@kevinbosak Yes, we upgraded to 1.11. It seems to have resolved the issue for us, but only time will tell if it crops back up. 

Being on CentOS 7 meant we had to build our own RPM for this. If you're on the same OS I can probably get you a link to grab the RPM to save you the trouble of having to build it manually. Let me know.

**Comment by kevinbosak** [comment] 2020-03-18 14:17
@laszlof Thanks.  We're on Debian, but I think we'll be fine now that our monitoring is fixed to report any buried jobs.

**Closed** 2020-03-18 14:18 UTC

**Comment by AndreC10002** [comment] 2020-03-27 16:13
We were experiencing the same problem, binlogs not deleted.  Looks like 1.11 fixed the issue.  We see beanstalkd deleting binlogs now.

Perhaps it helps to mention the problem may have started when the server ran out of disk space and Beanstalk was stopped and some inlogs deleted via shell.

Thank you guys.  Your help with this issue is much appreciated!

**Comment by laszlof** [comment] 2020-03-27 16:45
@AndreC10002 Glad its working for you as well.

In case anyone on EL7 comes across this thread, heres a link to the RPM we built for this:

https://franksworld.org/packages/beanstalkd-1.11-1.el7.x86_64.rpm

Obviously use all the precautions required when installing an RPM from an unknown source. This one is signed by my employer. (Nexcess)
